## Ask for Email Addresses"

You should ask for the **email address** of the person responding to your survey on behalf of a law firm, law department or legal vendor.  As to the order of that question, place it as one of the first questions because otherwise people who spend time slogging through the questionnaire might not want to find at the end that you want them to identify themselves, that they are not **anonymous**.   [Whether you make the question a **required** question raises other issues beyond the scope of this section.]

To be sure, some respondents might not wish to divulge their email address.  They do not want to be **spammed** with mailings or have their address peddled.  It would also mean that they would not be able to receive the report you produce, and it raises suspicions that their answers might be **fraudulent**, or put more genteelly, not be as accurate or complete as the answers of those who put their name to their response.  Typically, **partial answers** come from people who choose not to leave their email address.

It is a good practice to add an **instruction** to the question asking for email addresses: “We will use the email address only to send you your report or to inquire about a possible mistaken answer.”  Clearly, when someone puts in an email address, the respondent is no longer anonymous.

With the email address, you can send them the final **report**.  After all, they are probably taking part to learn the aggregate results.  Without an email address you cannot reciprocate.
Before that, you can reach out to the person if there is if you need to.  For example, in one compensation survey I led, a respondent entered \$11,000 for a base salary.  Realizing that figure was too low, I wrote and confirmed that the figure that was entered was missing a zero; it should have been \$110,000.  Other times, the respondent left several important questions unanswered.

Furthermore, with email addresses, since they are unique, you can describe in your report how **representative** of the total population is your survey sample.  Assuming you have gathered **demographic information** such as level, practice, location, or level, you can produce those demographic breakdowns of participants.  Then, too, you might enrich your survey demographics with **supplemental information** from an external source; as an example, Human Resources might allow you to include age or gender or AmLaw 100 data might be available.

You may also want an email address to be able to identify organizations that have taken part.  If so, you should ask for the business email of the person rather than their personal email.  Software can easily separate the text after the “@” symbol and you can match that text to the full name of the organization.

Knowing the organization also helps you detect **duplicate responses**, which is important (believe me, it happens!).  An email address affords a way to determine if someone has entered more than one response to a survey.  Multiple responses from the same person happened to me when a survey was kept open for a couple of months, and several people actually forgot that they had completed the survey.  By the way, you can deal with duplicates by keeping the latest one, keeping the one that has the fullest set of answers, or writing to the person to ask them.  You can also deal with duplicate responses by barring more than one response from the same **ISP address**.

As a fourth reason for asking the respondent’s email address, you will find it enlightening to **write respondents**, not just to thank them for taking part.  More important than courtesy, a follow-up, thank-you email lets you ask another question or two, such as what they would like to learn from the report or how they would improve the survey.  **Feedback** about the survey process and its topic proves to be invaluable.

If you know the total group that was invited to take part in the survey, such as all the internal employees of a company above the level of Director, then if you have the email addresses of the resulting subset of respondents, you can write to the remaining nonparticipants and urge them to take part.  You do not need to clutter the mailbox of respondents with follow-up reminders.

Once or twice, I have had email addresses that were incorrect so my return message to them bounced.  You may be able to correct this if you can reach out to peers or the organization where they work, or you might recheck the email list you relied on.  In some of my benchmark surveys, however, people had left the company by the time I compiled the report, so the email address was no longer valid.

With a related wrinkle, you may find that an invitee asks an administrative assistant to complete the survey, so you do not have the email address of the original invitee.  Others may ask you to send the report to their personal address and you will need to keep track of that special treatment.

<!--Book: 2 Type Response Data from Survey Posts Plan.xlsx-->
<!-- Source: TVPI22 -->