---
title: 'Savvy Surveys: Methods to Increase Participation'
author: Rees Morrison
date: '2022-05-17'
slug: []
categories:
  - Surveys
draft: no
---

We have already discussed invitations to potential participants sent by email.  If the survey is conducted within a law firm or law department, all the invitees’ addresses are at hand.  If, however, you are a vendor or consultant who wants to survey firms or departments, you want to reach as many as possible beyond a kernel email list that you have developed yourself.  Let’s consider a number of techniques to increase your email reach.

<!-- more -->

1.	In your **initial email** invitation to potential participants, you can urge them to forward the email to someone they know who might also want to take part.  This is a snowball approach to gaining participants, and it can be more effective if you give them a reason to take those few moments:  “Your benchmark data will be more robust if more professionals like you are involved.”

2.	When a person submits a survey response, thank them with an **acknowledgement email** and let them know it will benefit them to invite peers to take the survey.   What else may be included in the acknowledgement email is covered elsewhere.

3.	At the end of the questionnaire, when you thank the respondent for submitting a response, you can suggest that they forward the original email to interested friends, colleagues, or similarly-situated people.  Moreover, you might give them an incentive such as “If you send the invitation to two or more peers and notify us, we will send you a special report.”  I have offered to write people if the respondent gives me the email addresses of others.

4.	When you email a participant the **report** – you will do that, won’t you? – remind them that peers or colleagues they know might like to learn the same insights, but they have to participate.  Make it easy for report recipients to extend invitations to others.  Of course, this requires you to maintain an **evergreen survey** that periodically releases cumulative reports as more survey submissions  arrive, or at least a **supplementary report**.

In summary, your own email efforts open up four opportunities: (1) the invite email, (2) the thank you at the end of the survey, (3) the acknowledgement email, and (4) the report deliver are all chances to spread the gospel.

5.	If you **collaborate** with someone or have a **sponsor** of your survey, they might have a list of potential survey takers.  When that has happened with my surveys, someone always frets that we will duplicate our emails and irritate the harassed recipients.  In the end, I have concluded, don’t worry about an invitee receiving two emails; it might in fact help persuade them to go ahead with the survey.  The deeper reservation of collaborators and sponsors is that they do not want to share their cherished outreach list with a third party.  

6.	You can ask invitees whether they belong to a formal or informal group of peers who might be interested.  Such a group might publicize your survey and greatly increase your leverage and, with its imprimatur, your credibility.

7.	Under some circumstances, you might email the manager of the person you want to reach and give the manager reason to forward it.  Managing partners of law firms and general counsel of corporations are deluged with emails, but every now and then one may redirect it to your target whom you could not otherwise reach.  Obviously, that forwarding is a tacit endorsement of your survey and encourages the recipient to act.  

8.	Social media such as Twitter and LinkedIn offer a range of possibilities for reaching potential participants.   You or the sponsor may have an online presence and followers, or you might tag team with posts on an existing group or appropriate selection of hashtags.

9.	Directories of targets may be available, such as the law firms and law department leadership.  For a cost, the directory may be available electronically and you can harvest rafts of emails.

10.	The website of a law firm can provide a trove of email addresses for specific staff such as the Chief Information Officer or Chief Financial Officer.  To harvest the information can be tedious, but hordes of gig workers can be enticed to help.

11.	Many companies sell lists of curated emails, and if you license one that targets your market you can bolster your email outreach efforts.  In the early years of my law department benchmark survey, I acquired several lists of general counsel and wrote them (I take the Fifth regarding the anti-spam laws).   To be candid, it was difficult to evaluate the effectiveness of those expenditures of time and money.

12.	An article that is published while the survey stays open may generate awareness.  Readers who are intrigued by the topic and want the report will run, not walk, to the nearest **survey link** (in the near **future**, they will take a photo of a QCR code).

<!-- Book: Deploy -->
<!-- Source: Generic -->