---
title: Relegate Additional Material to the Appendix
author: Rees Morrison
date: '2022-06-10'
categories:
  - Surveys
draft: no
---

Put in the **appendix** to your **report** material that a few readers might want to consult, but for most readers is either irrelevant or too much to read.  If it clutters the report, digresses from the major findings, or obscures the flow of the report but you don’t want to jettison it, consider adding the material to the appendix.  The **table of contents** of the report should make clear by sub-entries what is in the appendix.  I have catalogued below the most typical appendix material and have done so in roughly the order that my projects for law firms or law departments have included the material.

•	References and end notes.  It would take another blog post to discuss the adroit placement of footnotes compared to endnotes compared to in-line references.  Suffice it to say that the appendix could house additional reference material such as these.

•	Technical and statistical terms.  A glossary represents the prototypical listing of your **technical terminology** and their definitions.  You might create something similar in the appendix, so that if people need to find out what “margin of error” means, they can learn from the alphabetical listing.  “Technical” covers any domain-specific jargon or special phrases and terms.

•	**Acknowledgments**.  The appendix could catalogue those who have helped you during the survey project as well as confess to shortcomings of the project.  We have written elsewhere about the multitude of individuals who might find themselves in acknowledgments.

* **Methodology**.  This item is not a history of the survey project.  Rather, it enables readers to judge how much credibility they should accord the survey's findings.

•	Details.  If the body of the report summarizes a large set of variable answers, it might be valuable for some readers to have access to the **granular data** (you might even post it online for download or interactive use).  For instance, often surveys by law firms and law departments ask about titles.  While you can summarize the basic permutations of titles, the specific instances may be far too numerous.  Rather than running a multipage **table** in the report proper, you might list all the individual variations in the appendix.

•	Your **software stack**.  “Stack” is a term used by programmers to describe the suite of software that enabled them to accomplish something.  It suggests a hierarchical collection of modules (or separate packages) that fit together to accomplish a purpose.  I have written elsewhere about the multifarious software that makes this blog possible.  

•	History of the project.  No one, except your mother, wants to read about how the sausage was made, but a few dramatic or exotic events might have taken place that justify being chronicled in the appendix.  Or perhaps key decisions were taken during the course of the project and they deserve to be explained.  A historical note may include the impetus for the survey project or significant changes along the route.

•	The final appendix element could be information about **contact information**: whom to email or call regarding questions about the survey, interviews, or permissions to use material.
