---
title: 'Spread Word that Your Survey is Open'
author: Rees Morrison
date: '2024-02-01'
slug: []
categories:
  - Surveys
draft: no
---

If you are conducting an external survey, you want as many participants as you can get, so long as they are appropriate for your research. You have e-mail addresses of the starter set of invitee/potential participants, but you would like the participant circle to be as large as possible. Here are some techniques for spreading the word.

Invitees Forward It:  In your e-mail invitation for people to take the survey, you can urge them to forward the invitation to others they know who are similarly situated. You can incentivize them to do so by explaining that the more respondents, the more data, and thus the more robust the results.  For example, the survey report can break down the results more finely.   One year I tried to reward those who forwarded the invitation by asking them to let me know if they did so, and in return I sent them an article. 

Each Reach One:  Another way to tap into the networks of those you email is to encourage each one to reach one. Instead of pushing them to e-mail it to multiple people, make the ask more manageable by describing it as: “Send it to one person who would appreciate hearing about the survey.” This more limited form of the snowball effect can motivate people better than asking them to summon to mind multiple people or cope with blind carbon copies.

Group Ties:  Those you invite to take the survey and those who take it may belong to formal or informal groups of fellow travelers. Those groups meet periodically or have listservs or mailing lists and if someone is an enthusiastic supporter of your survey, they might pass along a heads up or even an endorsement to the group. 

Closing to Questionnaire:  Hosting software lets you display a message to the respondent when they submit their survey.  That’s an opportune moment to urge them to spread the word.  “Now that you’ve taken the survey, do you know someone who might benefit from doing the survey?  Just forward them the invitation you got.”

Acknowledgement Request:  An earlier portion spoke about the good practice of writing to thank respondents and acknowledge receipt of the survey. In that thank you e-mail, which lends itself to a template, you can urge them to let others know about the survey being open and that it is both easy to complete and aimed to produce insightful results. The person has freshly finished the survey and can vouch for it.  In the thank you e-mail you might add some other ideas that are discussed here.  You might suggest that they announce the survey to their contacts on social networks, such as LinkedIn or Facebook.   I have tried asking directly for email addresses or names of others I could invite, but most people are reluctant to share such information.

Specific Counterparts:  In a survey of chief operating officers of law firms, the questionnaire asked about their prior position. For those who responded and said that they had come from another law firm, I wrote back and asked them who had filled their position at the prior firm and who had been in the position they have taken in their current firm.  Sometimes folks replied with names or emails so I was able to discover more potential participants.

Shared Characteristics:  When respondents share something in common with other potential respondents and would like to see the results filtered that way, the ones you reach may be more inclined to pass the word along about your survey. For example, law firm chief operating officers whose firm belongs to a network of law firms may help you out by reaching their counterparts at other network firms. Similarly, if the law firm uses the same financial accounting software, the respondent runs time and billing in common with counterparts at other firms that use the same software. I have tried to drum up enthusiasm in metropolitan areas or even in a country, such as Canada or Australia. As a final example, one year I wrote to all the women who took part in a survey and let them know how important it was to get a fuller range of representation among women.

Publications:  One time, I ran across a book for chief operating officers while I was in the midst of surveying that role in law firms. I reached out to the publisher to see if we could hit upon an arrangement where they would publicize my survey and I would publicize their book.  Magazine articles and online outlets are of course well-known ways to spread the word about a survey but their publication schedules require the survey to stay open a long time.

Consultants and Vendors:  Consultants are another fruitful source of introductions.  They have mailing lists, and they might swap some of your findings or shareable data for them launching an outreach to their mailing lists.   They might even run forms of advertisement such as banners on periodical mailings or other ways to reach more prospects.  

<!-- End of post   -->