---
title: Recognize the Planets of Knowledge Orbiting the Solar Survey
author: Rees Morrison
date: '2022-06-21'
slug: []
categories:
  - Surveys
draft: no
---

If a survey by a law firm, department, or vendor were an academic major, then related to it would be many minors.  Put differently, those who sponsor online surveys in the legal field need to till competently in the core acreage, but ancillary fields of knowledge stretch all around it.   Or as the title’s metaphor suggests, survey know-how shines brightly in the center, while planets of associated knowledge circle around.  The core comprises representative, accurate data analyzed thoughtfully.  Sketched below are domains of knowledge that a good project team should be aware of, if not have a level of proficiency and bring to bear.

* Consultant relations.  Some survey **sponsors** may supplement their in-house capabilities with an external advisor.  How to make that decision and then dealing with the **consultant** fall into a minor related to surveys.  My sense is that most law-related surveys are do-it-yourself.

* Vendor selection.  As with consultants, it would be helpful for the project team to understand the process of vetting **hosting software** vendors, including sending requests for information, taking part in demos, negotiating terms, and so forth.  But you can choose the software less elaborately and with flimsy background experience.  Related to this, your understanding of the plumbing of your hosting software need not drain you.  It boasts many features that you will neither use nor be aware of.  Neophytes can learn the essential capabilities of the software and construct a competent survey.

* Design of online elements.  A book by Mick Couper, *Designing Effective Web Surveys* (Cambridge Univ. Press, 2008), runs nearly 400 pages on choices in **on-screen design**.  How you layout and format the questionnaire involves aesthetics, visual perception, and psychology.  Couper and others delve deeply into HTML and CSS as well as empirical research on the user interface.  Good to appreciate, but not vital.

* Topic content.  Absolutely, the sponsor must understand the field that is being surveyed.  What the questions ask goes to the heart of the survey.  However, a proficient survey designer and **analyst** can succeed even if their knowledge of the topic barely registers.  True, what questions are posed and how framed means everything for a survey, but the person who translates the questions into the host software and later assembles and portrays the resulting date does not need familiarity with the subject matter. 

* **Project management**.  If someone on the survey team has experience with Gantt charts, chokepoints, corralling maverick teammates, and time management, that’s terrific.  But for a survey project to fare well, this enormous area of thought and plethora of writings remains a secondary domain of knowledge.

* **Programming** aptitude.  Whoever mines the data returned by the respondents and smelts it into analytical gold can do just fine with competent programming abilities.  They do not have to be an ace.  If they use R or Python, for example, packages abound with functions for doing the common tasks of programming such as pre-processing, subsetting, calculating, and plotting.  Nothing need be written from scratch.  A reputable survey project does not revolve around novel algorithms or gnarly coding challenges.  It is even possible to rely on the hosting software or simpler tools such as spreadsheets or data analysis packages for many coding requisites.  If an unusual catch pops up, Stack Overflow will pull you through.

* Statistics.  Insightful surveys can do swimmingly with nothing mathematically more complicated than calculations of averages and medians.  Wading deeper, more numerate surveys sail through quartiles, standard deviations, and confidence intervals.  Multiple regression models reach the deepest seas.  But given the ocean of **statistics**, the typical rowboat survey that a law department or law firm launches barely leaves shore.

* Graphics construction.  Just for the R programming language, more than a score of books have been published about how to create graphs and tables; multiples of that number are available as books on graphing skills in other programming languages or in general.  Again, a **survey report** certainly needs to handle the visual depiction of data competently, but more sophistication (such as infographics) lies beyond the scope of most survey projects.

* **Report layout** and design.  Without a doubt, the public face of a survey project is the report made available to respondents, management, and interested parties.  The report should look attractive and present the data and findings in an inviting format.  But the components of an effective report in PowerPoint or another tool remains peripheral to the essential survey project.  

* **Publicity**.  Ask your Chief Marketing Officer about the enormous scope of “marketing” and you will appreciate that the survey team needs to know not only that deep thought and long experience looms out there, but also that the team’s core competencies needn’t lie in that direction.  Besides, internal surveys by a firm or department rely on distribution, not publicity.

* Change management.  Certainly, if a survey’s findings drive toward changing how people act, it is beneficial to understand and put into practice the principles and teachings of **change management**.  But proficiency in that ever-growing specialization is not necessary, and therefore this field of knowledge sits outside the core of survey competence.

Other domains of knowledge, the minors to the survey’s major (or the rolling fields surrounding the tended garden), are undoubtably out there (clear and effective writing comes to mind).  They all open vistas of detailed treatment and profound learning in each direction.  Meanwhile, it can be seen above what are some of the boundary markers are and what is out of scope.  
