---
title: Construct Index Variables, but Carefully
author: Rees Morrison
date: '2022-06-01'
categories:
  - Surveys
draft: no
---

An **index variable** (sometimes called a “synthetic variable”) takes related questions on a survey and weaves their answers into a new, consolidated variable.  What can you do with an index variable?  One reason to create an index variable is to consolidate the data from multiple questions that would otherwise be difficult to picture and comprehend.  These variables help you understand and communicate a complicated situation with quantification.  You can use that new variable as a classification category for further analyses.  You can show how other metrics correlate to that index.  

Let’s imagine how you might create an index variable.  A law firm surveys its partners regarding their opinions of the firm’s strategic planning process.  Here is an opportunity to create an index variable made up of the partners’ views so that we can grasp the overall attitude of the partners toward the firms’ process of setting strategy.  Let’s call those who dislike the current process “Critics”, those who accept the extant system or are neutral we’ll call “Centrists”, and those who support the system are “Champs.”  An index variable classifies the Critics, Centrists, and Champs based on their responses to two sets of questions and a text question.  

•	One set of questions asks for a level of agreement with several aspects of the strategic planning system on a scale of 1 (low, finding fault, strongly disagreeing) to 7 (high, admiring, strongly agreeing).  The average of the levels selected on all the aspects lets us classify the partners as relative Level Critics, Level Centrists, and Level Champs. 

•	A second set of questions asks for assessments by the partners of several other elements of the strategic planning system *as it is* on a scale from low to high and then what the system *should be* on the same scale.  The “should be” assessment subtracted from the “as it is” assessment produces a “gap: number and lets us classify the partners as relative Gap Critics, Gap Centrists, and Gap Champs – larger gaps mean more criticism of what presently happens.  

•	Third, we score an open-ended text question on a sentiment scale (a natural language processing technique), which lets us classify the partners as relative Sentiment Critics, Sentiment Centrists, and Sentiment Champs.

Finally, adding together each of the three values for a partner yields the partner’s index score.  **Analysis software** can place each partner into a quintile on the index score.  Thus, the top 20% of the index scores would be "5s", the next lower 20% would be "4s," and so on.  The top quintile comments include the relatively strongest advocates for how long-range planning currently takes place.  We can proceed to describe overall attitudes of the partners to the firm’s strategic planning process by means of this index variable.

However, the index variable as imagined above would be an unadjusted measure, and not every question in it may deserve the same **weight** in the summing of values.  A **survey analyst**, collaborating with a **Subject Matter Expert** and others on the **project team**, might decide that one of the components of the index should influence the index score differently.  Perhaps the “gap” score is deemed twice as important in the overall score as each of the other two scores.  Or the data resulting from the other two questions feel squishy, weak, or less certain to have captured the views of the partners.  Your **analysis software** can weight that double and then calculate the weighted index score.  A weight, to be precise, can be 0.3, 1.8 or any other amount.

Survey analysts who follow this path to extend their data ought to keep in mind that they are constructing a variable from other variables.  It could lead to an untrustworthy sandcastle to the degree one or more of the component variables lack credibility or reliability.  Sponsors and readers of reports forget this risk; the new index variable takes on a life and reality of its own.  People quickly accept it as hard and real as they talk about it uncritically.  As a rebuttal, an analyst could point out that when you combine multiple indicators, the resulting index score washes out or moderates aberrant data, much like an average of a group of numbers smooths extreme values.  

If your analysis generates an index variable, you must explain carefully in your **methodology section** how you arrived at it, an explanation which probably appears in the report’s **appendix**.  

Index variables introduce a more sophisticated manipulation of data, but not without analytic risks.  Used skillfully they help us understand and quantify a domain better than we did before.
