---
title: Add an Acknowledgement Section to Your Report
author: Rees Morrison
date: '2022-06-10'
categories:
  - Surveys
draft: no
---

In the **appendix** to the **report** on your survey findings, your law firm or law department has the opportunity to say “thank you” to those who helped and “my bad” for any shortcomings you recognize.  Many wheels must turn in a survey project, with lots of cogs and gears; an **acknowledgement**, therefore, can call out a range of contributors.  Based on my familiarity with many law-related surveys, I have listed below the most common items in acknowledgements. 

•	Respondents might email you with an issue or suggestion or they might write about either in a text comment.  If so, you might thank them without naming them.

•	If you follow the practice of sending each respondent a **thank-you note** and ask them a question about what they thought of the survey, every now and then you collect useful answers.  The best of them might deserve kudos in the acknowledgements.  In one of my survey projects, I recall, a person suggested what turned out to be the appropriate conversion rate for Canadian dollars.

•	You might tip your hat to your **host software** company.  This gratitude would be especially warranted if their help desk had promptly answered questions you posed about how to accomplish something with their software.  Or they might go so far as to upgrade their offering with a capability that strengthened your project.

•	A **subject matter expert** who brought to the table deep understanding of the survey topic also deserves recognition.  Whether they want to have that spotlight is a different question.

•	The analyst who toils to clean the data and produce the benchmark values and graphs certainly should be put on a pedestal.

•	The project team, either individually or as a whole, deserves a thank you.  Especially this would be true about the team leader, if they lived up to that title.

•	Cosponsors might be admired and thanked for what they brought to the project, such as a mailing list, refinements to the questions asked, domain wisdom, or funding.

•	Volunteers (or conscripts) who **pretested** the survey and reviewed the report also deserve a nod.

•	You should thank respondents who forwarded your **invitation email** or took other actions to increase the number of participants.  Along those lines, any trade group or informal network of like-minded potential participants deserves a bow and applause.

•	I show my enduring appreciation for the R programming language, and the wonderful open-source community that supports it.  You may feel less heartfelt gratitude toward your **analysis software**, but at least mention it.  You might feel it is appropriate to put in a nice word for Stack Overflow or Reddit if they helped you solve a challenging problem of programming.

•	Finally, to state the obvious, you will undoubtedly fawn over the insights you gained from [Savvy Surveys for Lawyers](https://savvysurveysjd.com/)! 

All the above are favorable acknowledgments.  Someone contributed to the completion and success of the survey project.  So long as individuals agree, it is more generous to cite them by name.  Otherwise, shift to a generalized form: “I appreciate deeply the suggestions made by several respondents who asked not to be named.”  

But you always will have some observations you can make in your acknowledgements that are negative in that they recognize weaknesses in your survey (you may have a separate item in the appendix pertaining to challenges of **methodology**).  For example, maybe too few technology companies submitted responses in relation to that industry’s market capitalization.  Perhaps your **margins of error** are wide due to **missing data**.  My point is that you can acknowledge both strengths of others and your own weaknesses.
