---
title: 'Savvy Surveys: Questions Required to be Answered'
author: Rees Morrison
date: '2022-05-09'
slug: []
categories:
  - Surveys
draft: no
---

Many surveys by law firms or law departments include one or more questions that must be answered.  Why?  Primarily, the sponsor believes that certain background information will play a crucial role in their analysis of the data, so they insist on respondents providing that information.  “What is your level?“ “What is your practice department?”  

<!--more-->

A **demographic question**, such as “In which office do you work?”, might have to be answered because the survey analyst needs to determine **representativeness**.  “Do we have at least 25% of each office in our response set?”   They might also want to send **reminder emails** only to those who have not submitted a  response, so they require a name.  Information that everyone must give also helps spot **duplicates**.  

Second, a required question might also serve as a **gatekeeper**, so that if you do not answer acceptably or if the sponsor has enough responses in that category, you are **disqualified**.

Third, when you require a valid **email address** or the **name** of the respondent, you make it much less likely that someone will answer with nonsense or **insincere answers**.  If it is absolutely necessary to give an answer, what to put in should be known to the respondent off the top of her head.

Sponsors of surveys often have an understandable desire to make too many questions mandatory.  They deeply want to find out what participants think or know so they push for input; they are tempted to slap on too many flags of “required”.  On the flipside, respondents want as few required questions as possible – or even none.  Those obnoxious gates of questions you must address keep your nose to the grindstone and slow you as you try to move rapidly.  Hence the inherent **tradeoff** and the tension: sponsors crave information, responders dislike coercion.

You might think that a sponsor would make a question mandatory if it was addressing the most important aspect of the topic.  In the surveys I work on or review, I don’t see that approach being taken, and not only because it might be hard to single out the most crucial inquiry.  

Let’s reflect on a few collateral issues that arise with must-answer questions.   These issues combine **design decisions** and **strategic choices**.  

•	May a respondent proceed with the rest of the survey if she ignores a required question?  That should be impossible if the designer truly intends for it to be mandatory.  Conceivably, they might receive a **feedback message** that their survey will not be accepted without the required answer, but that they can proceed.  They might find that the survey is interesting enough or what they will get back is rewarding enough that they will decide later to complete the required question (assuming they can **navigate** back to it).  I should point out that a survey submission that lacks a required answer may still offer useful insights from its other parts.  A required question unanswered might bar submission, not completion.  Or it might be accepted as a **partial response** and the data analyst decides whether to use the remaining answers.

•	Where should you place the required question(s)?  Put them up front, because you do not want someone to spend time and energy slogging through a survey, only to find at the end that that it insists on information that they do not want to provide.  

•	Do you tell invitees in the email or in **prefatory text** that there are a few required answers and what the questions are?  This might deter participation but it is certainly honest and transparent.

If sponsors should be chary of loading up on required questions, are there alternative approaches?

1.	Explain in the **question instruction** why the question is so important as to deserve being obligatory.  Some respondents might not appreciate the gravity or pivotal nature of their response.  “We need to know the number of windows in of your office so we can design and build out the new floors better.”

2.	Assure the respondents in both the invitation and the question instruction that you will not abuse the personal information that they fill in .

3.	Give an external incentive such as a drawing for a gift or a contribution to a charitable foundation.

4.	Explain an incentive internal to the survey.  For example, change the number or type of questions that come after the required question, so that the participants know there is a benefit to filling in that particular question.

5.	Ask for substantially equivalent information in pieces or indirectly.  For example, if you learn how long someone has been in the law department plus the level they report to, you might be able to deduce who the person is, rather than requiring their name or  email address.  This may feel sneaky, it avoids the hammer of ANSWER THIS!.

6.	A nudge if they leave the question blank could change their mind – “Your answer is very important for our analysis.  Are you sure you want to leave it blank?”

7.	Improve the message that the **host software** returns if a respondent bypasses a required question.

8.	A **text box** lets them avoid answering the question as asked, but explain their reluctance or provide the information partially or wholly in their own way.

9.	**Conditional logic** might insert a reworded, required question a bit later – a second bite at the apple.

<!-- Book: 2 Required -->
<!-- Source: TVPi -->
