---
title: Choose a Complementary Team for the Survey Project
author: Rees Morrison
date: '2022-06-01'
categories:
  - Surveys
draft: no 
---

For a flourishing **survey project**, assemble a team whose members contribute balanced and complementary talents.  It doesn’t take a village, but it takes at least a handful of contributors.  Different viewpoints and skills from the legal team or law firm should be committed to the success of the project.

Remember, the information you aim to collect from the online survey needs to be generally acknowledged as objective – not biased toward or against pre-ordained conclusions – and comprehensive – covering the topics that most recipients of the report would like to see explored.  Thus, the team should strive for representative balance and thorough coverage while it advances the goals of management.  

Management scholars, executives, and consultants have written overwhelmingly about solid teams and what makes them tick.  Let me therefore modestly note six characteristics that are crucial for a productive **survey project team**.  

1.	The team should be willing and able to think through the tools and timing of their effort, including the costs and contributions of team members.  They need to exercise a modicum of project management skills.

2.	The team needs to deliberate on the questions and the invitee group who will be asked to respond to them; what areas of inquiry will be plumbed and how will the answers be aggregated and presented.  They need a solid grasp of the survey’s purpose and who will learn what from the effort.  These are all challenging topics that a committed and varied team confronts.

3.	The perpetual challenge is obtaining sufficient time for the team members to perform well.  Members are busy and likely to have different – or even conflicting – priorities and goals.  No matter how you spin it, time spent on a survey project is non-billable, administrative time, which comes at a premium.  To carve out blocks of time for all team members to meet … that’s hard.

4.	The members need to have at least a modest interest in either the information sought from the survey, its methodology, the instrumental use of the survey, or ideally all those areas.  People dragooned into a project may derail it.

5.	Law firm and legal department teams will fall short in survey **methodology** (good questionnaire design, statistical robustness, effective data visualization) but will excel in making sense of the data (at least by their own lights).  A **consultant** can strengthen a team with experience on methodology, obstacles, and tools.  Hence, match the knowledge of the sponsor team as to its goals and areas of inquiry with the process and software skills of the consultant.  A consultant might know little about partner compensation or paralegal morale or time allocation, but they should know survey tasks and timing, as well as how to create and deploy an online instrument with a **survey tool**, how to process the returned data and transform it into sensible graphs, and how to package a **report**.

6.	The team should not be dominated by any member: not the General Counsel or the Managing Partner, to whom team members may unwarrantedly defer.

At the risk of generalizing too much, consider a hypothetical five-person team.  Person A is senior, thinks long-term and knows the history and culture of those to be surveyed; Person B is more junior, in touch with the “newer generation”, perhaps more likely to want change in the status quo and likes technology; Person C is comfortable with mathematical thinking and Excel; Person D writes clearly and cares passionately about the whether the survey project brings about meaningful change; and Person E is known as a maverick, a precise and careful person, and a capable project manager and chair.  An adept chairperson, respected by the members, goes a long way to harness the requisite skills of the team members and navigate the shoals of team performance.  
