---
title: 'Surveys for Lawyers: First Email Reminder'
author: 'Rees Morrison'
date: '2022-05-06'
slug: []
categories:
  - Surveys
draft: no
---

When I help law firms, law departments and legal vendors conduct online surveys, they usually ask about the tempo of sending **reminder emails** to those invited to participate.  In other words, after the **initial email** introduction with the survey link that you blast out to outside counsel, all the paralegals in the firm, the R&D clients above Manager, or whomever, how long do you wait to remind them that they should complete the survey?

<!--more-->

My general guideline is based on how long the survey will be open (the **open period**).  I like to divide that into three roughly stretches.  Thus, a sponsor whose survey is intended to be open for 30 days would dispatch the second invite, the reminder email, 10 days after the first invitation.  The first reminder invitation should probably go to the original invite list, in part because those who have taken part can then speak with their peers and confirm that it was no ordeal.  The second reminder would go out 20 days after the first invitation, thus dividing the open-period month into three roughly equal periods of time.  [I have never seen an email tease precede the first round, e.g., “In a few days, keep an eye on your email box for an opportunity to give your opinions on our diversity campaign.”  Such a save-the-date message might set the stage and lead to a higher response rate.]

The **final email** encouragement, to be consider in filigree detail later, ideally only goes to the nonrespondents, which implies that you have asked for the email addresses of respondents (or some other identification) so that you can drop those people from the total, original **list of emails**).  No need to clutter the mailbox or confuse respondent’s (a few of which might lose track and respond a second time).  

Two additional points:  If you use an **email manager**, such as Constant Contact or MailChimp, its software may help you curate the list of email addresses.  That genre of software may be able to tell you who has opened the survey, even if they have not submitted any answers.  Second, under no circumstances would I name and shame the invitees who have not yet participated (perhaps they have been on vacation or maternity leave).

What should be the contents of the first reminder email?

1. The subject line should suggest a bit more urgency than the original email.

2. The reminder email should start by thanking those who have taken the time to participate to date.  It also should urge them to encourage their peers to complete the survey.  

3. Remind them again of the benefits to them of devoting a few minutes to the survey.  “What’s in it for me?,” to cram the survey into all their other responsibilities, is crucial.  
Some people resend the original email message; better, in my mind, to refer to it but shorten the message.  More to that point on brevity, in an era of email overload, the shorter the reminder email the better.  Additionally, if you bold or color the key takeaways, busy people might absorb the message faster and act on it.

4. Describe the rights of respondents: they can start, stop midway, then resume.  They don’t have to answer every question; no research is required; a **progress bar** will tug them along.  Maybe you should create a link to **frequently asked questions**.  You might want to reassure invitees that all results will be **anonymous**, tell them the number of questions on the survey, and reinforce what they will learn about the findings from the survey, and estimate the average time required to complete it.  In regard to duration, at least one survey hosting service can tell you how many minutes each respondent had the survey open.  That data gives you the empirical basis to say that, based on what’s been submitted so far, “the survey should not take more than seven or eight minutes to complete.”   Here’s the general point: address objections or questions you have received about the survey process, or anything that makes people reluctant to dive in.  

5. Everyone privileges **transparency** and many people are at least curious about the scope and progress of the survey.  Accordingly, the reminder will be more effective if it states the number of people who were originally invited, the current number of valid responses, and perhaps additional information, such as responses by office, title, or other **demographic criteria**.  Hopefully, the distribution of responses in hand conveys involvement across the board.  It might encourage a few recalcitrant invitees to take part if they know that they will be among a large, broad-based group, and therefore **anonymous**, and that many peers have voted with their feet, thereby implicitly endorsing the survey.

6. I have mixed feelings about stating in the reminder email a goal for how many valid responses the sponsor seeks.  Yes, you wish that everyone would weigh in, but no survey should expect 100% participation, except in North Korea.  And, often it is difficult to project a goal if you haven’t conducted the survey before, or have invited hundreds, let alone both.  On the other hand, if a forerunner survey has been done, include in the reminder email a how many took part in the past compared to how many have taken part so far.  People may feel more inclined to open the survey link when they appreciate that their effort is part of a long-running, **trend** study.

In closing, do not overlook other channels of communication to boost participation.  Your firm or department may have bi-weekly staff meetings, notice boards, a portal that can display a pop-up window, a coffee room poster, a text message chain, or even personal phone calls.  Whatever helps you boost survey **participation rates** is fair game.

<!-- Book: 1 Deployment -->
<!-- Source: TVPi22 --> 
