---
title: Wrestle with "Not Applicable" and "Don't Know"
author: Rees Morrison
date: '2022-06-21'
categories:
  - Surveys
draft: no
---

A rule that admits no exception commands survey designers to end the selection items of a **multiple-choice question** with one item: “**Other**.”   Survey experts hold much less adamant views regarding whether to tack on any or all questions a variation of “**Not applicable**” or “**Don’t know enough to answer**.”  Yet for a respondent either of those choices may be the most appropriate on any given question.  

If you don’t include them, the respondent may pick an item, but that choice is based on too little knowledge or too little relevance to that person.  In effect, you have forced an inaccurate or unreliable answer.  But you have no way to gauge or mitigate that risk (other than possibly a comment box, but someone will still have to interpret the comment for the answer to be useful).

A “not applicable” selection has factual overtones.  It says that under the facts germane to the person taking the survey, the question has no meaningful answer for that person.  “How much would be an appropriate train ticket subsidy?” does not pertain to and should not be answered by a partner who commutes by subway.  Or the question, “How many people report to you?” might be answered with a zero or with an “not applicable” if the person works alone, with no one junior under them.   A rating question regarding e-discovery techniques should be checked “Not applicable” by a non-litigator.

“Don’t know” creates an interpretational gap.  The respondent might mean that an answer exists, but he or she is ignorant of that answer.  Or it might mean, “I don’t care enough to choose an item.”  They are like the rules of pleading and “DKI”: “A party that lacks knowledge or information sufficient to form a belief about the truth …”.   

 “NA” could mean that the information is not available, as in it does exist somewhere or could be obtained, but the respondent doesn’t know the information.  “What was the after-tax income of your company in FY21?”  As to this possibility, I try hard to write only questions that respondents can answer without research or consultation.  We should note that some people might understand “NA” to mean “not applicable” so it is best to write out which expansion of “NA” holds.  

“Prefer not to answer” presents yet another alternative selection.  It suggests that the respondent knows their answer but declines to offer it, such as regarding gender or commitment to staying at the firm or department.  Apparently the question was too sensitive for the respondent to answer (even with iron-clad assurances of **anonymity**, an analyst somewhere reads the disclosure).  

If a respondent selects any of these non-substantive answers, the survey might trigger a **conditional logic** rule to change what question appears next.  If a line of questioning is thereby foreclosed, skip it.

Designers of survey questions debate the wisdom of allowing such choices because it offers an easy, no-thought-required escape.  Since all of us are satisficing types, we may opt for the escape valve a little too readily to avoid the acute pain of thinking.  But that is a cynical view; better to realize that the knowledge of respondents or the match of a question to their circumstances vary.  Whichever form of these selections you incorporate in your survey, if you include them, please make sure you deploy them with consistent phrasing and instructions.
